export const POST_REGISTRATION = "POST_REGISTRATION";
export const POST_REGISTRATION_LOADING = "POST_REGISTRATION_LOADING";
export const POST_REGISTRATION_SUCCESS = "POST_REGISTRATION_SUCCESS";
export const POST_REGISTRATION_FAILED = "POST_REGISTRATION_FAILED";

//Login

export const LOGIN_AUTH = "LOGIN_AUTH";
export const LOGIN_AUTH_LOADING = "LOGIN_AUTH_LOADING";
export const LOGIN_AUTH_SUCCESS = "LOGIN_AUTH_SUCCESS";
export const LOGIN_AUTH_FAILED = "LOGIN_AUTH_FAILED";

// Fetching Registration Data

export const GET_REGISTRATION_LOADING = "GET_REGISTRATION_LOADING";
export const GET_REGISTRATION_DATA = "GET_REGISTRATION_DATA";
export const GET_REGISTRATION_DATA_SUCCESS = "GET_REGISTRATION_DATA_SUCCESS";
export const GET_REGISTRATION_DATA_FAILED = "GET_REGISTRATION_DATA_FAILED";

// Event

export const REG_EVENT = "REG_EVENT";
export const REG_EVENT_LOADING = "REG_EVENT_LOADING";
export const REG_EVENT_SUCCESS = "REG_EVENT_SUCCESS";
export const REG_EVENT_FAILED = "REG_EVENT_FAILED";

//List Event

export const LIST_EVENT = "LIST_EVENT";
export const LIST_EVENT_LOADING = "LIST_EVENT_LOADING";
export const LIST_EVENT_SUCCESS = "LIST_EVENT_SUCCESS";
export const LIST_EVENT_FAILED = "LIST_EVENT_FAILED";

//SINGLE Event

export const SINGLE_LIST_EVENT = "SINGLE_LIST_EVENT";
export const SINGLE_LIST_EVENT_LOADING = "SINGLE_LIST_EVENT_LOADING";
export const SINGLE_LIST_EVENT_SUCCESS = "SINGLE_LIST_EVENT_SUCCESS";
export const SINGLE_LIST_EVENT_FALIED = "SINGLE_LIST_EVENT_FALIED";

//UPDATE EVENT

export const UPDATE_LIST_EVENT = "UPDATE_LIST_EVENT";
export const UPDATE_LIST_EVENT_LOADING = "UPDATE_LIST_EVENT_LOADING";
export const UPDATE_LIST_EVENT_SUCCESS = "UPDATE_LIST_EVENT_SUCCESS";
export const UPDATE_LIST_EVENT_FIALED = "UPDATE_LIST_EVENT_FIALED";

//Delete Event
export const DELETE_USER_EVENT_LIST = "DELETE_USER_EVENT_LIST";
export const DELETE_USER_EVENT_LIST_LOADING = "DELETE_USER_EVENT_LIST_LOADING";
export const DELETE_USER_EVENT_LIST_SUCCESS = "DELETE_USER_EVENT_LIST_SUCCESS";
export const DELETE_USER_EVENT_LIST_FAILED = "DELETE_USER_EVENT_LIST_FAILED";
